service: serverless-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  createTicket:
    handler: handler.create
    events:
      - http:
          path: tickets
          method: post
          cors: true
